# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  pull_request:
    branches: [develop]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.R_CI }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.4.0'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr@3.4.0, local::.
          dependencies: 'c("Imports", "Depends", "LinkingTo")'
          needs: lint

      - name: Lint package
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
